version: '3.9'

services:
  fastapi-app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always
  fastapi-app-2:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    restart: always
  fastapi-app-3:
    build: .
    ports:
      - "8002:8000"
    volumes:
      - .:/app
    restart: always

